import commands

# -----------------
# LOCAL ENVIRONMENT
# ----------------
Import('env')
cwpath_env = env.Clone()

cwpath_env.PythonExtension('cwpath', ['./cwpath.pyx'])
cwpath_env.PythonExtension('graphnet', ['./graphnet.pyx'])
cwpath_env.PythonExtension('regression', ['./regression.pyx'])

#cwpath_env.PythonExtension('cwpath.graphnet', ['./graphnet.pyx'])
#cwpath_env.PythonExtension('optimization.cwpath.graphnet', ['./graphnet.pyx'])

#env.PythonExtension('./optimization/cwpath/lasso', ['./optimization/cwpath/lasso.pyx'])

#cwpath_env.SharedLibrary('graphnet',['./graphnet.os'], LIBPREFIX = '')