# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'argon/panels/LightEnginePanel.ui'
#
# Created: Mon Nov 14 21:04:54 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_lightEnginePanel(object):
    def setupUi(self, lightEnginePanel):
        lightEnginePanel.setObjectName(_fromUtf8("lightEnginePanel"))
        lightEnginePanel.resize(350, 846)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(lightEnginePanel.sizePolicy().hasHeightForWidth())
        lightEnginePanel.setSizePolicy(sizePolicy)
        lightEnginePanel.setMinimumSize(QtCore.QSize(350, 0))
        lightEnginePanel.setMaximumSize(QtCore.QSize(1024, 16777215))
        lightEnginePanel.setWindowTitle(QtGui.QApplication.translate("lightEnginePanel", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_2 = QtGui.QVBoxLayout(lightEnginePanel)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(lightEnginePanel)
        self.label.setText(QtGui.QApplication.translate("lightEnginePanel", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.portComboBox = QtGui.QComboBox(lightEnginePanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portComboBox.sizePolicy().hasHeightForWidth())
        self.portComboBox.setSizePolicy(sizePolicy)
        self.portComboBox.setObjectName(_fromUtf8("portComboBox"))
        self.horizontalLayout_7.addWidget(self.portComboBox)
        self.initButton = QtGui.QPushButton(lightEnginePanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initButton.sizePolicy().hasHeightForWidth())
        self.initButton.setSizePolicy(sizePolicy)
        self.initButton.setText(QtGui.QApplication.translate("lightEnginePanel", "INIT", None, QtGui.QApplication.UnicodeUTF8))
        self.initButton.setAutoDefault(False)
        self.initButton.setDefault(False)
        self.initButton.setFlat(False)
        self.initButton.setObjectName(_fromUtf8("initButton"))
        self.horizontalLayout_7.addWidget(self.initButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.violetButton = QtGui.QPushButton(lightEnginePanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.violetButton.sizePolicy().hasHeightForWidth())
        self.violetButton.setSizePolicy(sizePolicy)
        self.violetButton.setText(QtGui.QApplication.translate("lightEnginePanel", "Violet", None, QtGui.QApplication.UnicodeUTF8))
        self.violetButton.setAutoDefault(False)
        self.violetButton.setDefault(False)
        self.violetButton.setFlat(False)
        self.violetButton.setObjectName(_fromUtf8("violetButton"))
        self.horizontalLayout.addWidget(self.violetButton)
        self.violetSlider = QtGui.QSlider(lightEnginePanel)
        self.violetSlider.setMaximum(255)
        self.violetSlider.setOrientation(QtCore.Qt.Horizontal)
        self.violetSlider.setObjectName(_fromUtf8("violetSlider"))
        self.horizontalLayout.addWidget(self.violetSlider)
        self.violetSpinBox = QtGui.QDoubleSpinBox(lightEnginePanel)
        self.violetSpinBox.setDecimals(0)
        self.violetSpinBox.setMaximum(255.0)
        self.violetSpinBox.setSingleStep(10.0)
        self.violetSpinBox.setObjectName(_fromUtf8("violetSpinBox"))
        self.horizontalLayout.addWidget(self.violetSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.blueButton = QtGui.QPushButton(lightEnginePanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blueButton.sizePolicy().hasHeightForWidth())
        self.blueButton.setSizePolicy(sizePolicy)
        self.blueButton.setMinimumSize(QtCore.QSize(80, 0))
        self.blueButton.setText(QtGui.QApplication.translate("lightEnginePanel", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.blueButton.setAutoDefault(False)
        self.blueButton.setDefault(False)
        self.blueButton.setFlat(False)
        self.blueButton.setObjectName(_fromUtf8("blueButton"))
        self.horizontalLayout_2.addWidget(self.blueButton)
        self.blueSlider = QtGui.QSlider(lightEnginePanel)
        self.blueSlider.setMaximum(255)
        self.blueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueSlider.setObjectName(_fromUtf8("blueSlider"))
        self.horizontalLayout_2.addWidget(self.blueSlider)
        self.blueSpinBox = QtGui.QDoubleSpinBox(lightEnginePanel)
        self.blueSpinBox.setDecimals(0)
        self.blueSpinBox.setMaximum(255.0)
        self.blueSpinBox.setSingleStep(10.0)
        self.blueSpinBox.setObjectName(_fromUtf8("blueSpinBox"))
        self.horizontalLayout_2.addWidget(self.blueSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cyanButton = QtGui.QPushButton(lightEnginePanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cyanButton.sizePolicy().hasHeightForWidth())
        self.cyanButton.setSizePolicy(sizePolicy)
        self.cyanButton.setMinimumSize(QtCore.QSize(80, 0))
        self.cyanButton.setText(QtGui.QApplication.translate("lightEnginePanel", "Cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.cyanButton.setAutoDefault(False)
        self.cyanButton.setDefault(False)
        self.cyanButton.setFlat(False)
        self.cyanButton.setObjectName(_fromUtf8("cyanButton"))
        self.horizontalLayout_3.addWidget(self.cyanButton)
        self.cyanSlider = QtGui.QSlider(lightEnginePanel)
        self.cyanSlider.setMaximum(255)
        self.cyanSlider.setOrientation(QtCore.Qt.Horizontal)
        self.cyanSlider.setObjectName(_fromUtf8("cyanSlider"))
        self.horizontalLayout_3.addWidget(self.cyanSlider)
        self.cyanSpinBox = QtGui.QDoubleSpinBox(lightEnginePanel)
        self.cyanSpinBox.setDecimals(0)
        self.cyanSpinBox.setMaximum(255.0)
        self.cyanSpinBox.setSingleStep(10.0)
        self.cyanSpinBox.setObjectName(_fromUtf8("cyanSpinBox"))
        self.horizontalLayout_3.addWidget(self.cyanSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tealButton = QtGui.QPushButton(lightEnginePanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tealButton.sizePolicy().hasHeightForWidth())
        self.tealButton.setSizePolicy(sizePolicy)
        self.tealButton.setMinimumSize(QtCore.QSize(80, 0))
        self.tealButton.setText(QtGui.QApplication.translate("lightEnginePanel", "Teal", None, QtGui.QApplication.UnicodeUTF8))
        self.tealButton.setAutoDefault(False)
        self.tealButton.setDefault(False)
        self.tealButton.setFlat(False)
        self.tealButton.setObjectName(_fromUtf8("tealButton"))
        self.horizontalLayout_4.addWidget(self.tealButton)
        self.tealSlider = QtGui.QSlider(lightEnginePanel)
        self.tealSlider.setMaximum(255)
        self.tealSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tealSlider.setObjectName(_fromUtf8("tealSlider"))
        self.horizontalLayout_4.addWidget(self.tealSlider)
        self.tealSpinBox = QtGui.QDoubleSpinBox(lightEnginePanel)
        self.tealSpinBox.setDecimals(0)
        self.tealSpinBox.setMaximum(255.0)
        self.tealSpinBox.setSingleStep(10.0)
        self.tealSpinBox.setObjectName(_fromUtf8("tealSpinBox"))
        self.horizontalLayout_4.addWidget(self.tealSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.greenButton = QtGui.QPushButton(lightEnginePanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenButton.sizePolicy().hasHeightForWidth())
        self.greenButton.setSizePolicy(sizePolicy)
        self.greenButton.setMinimumSize(QtCore.QSize(80, 0))
        self.greenButton.setText(QtGui.QApplication.translate("lightEnginePanel", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.greenButton.setAutoDefault(False)
        self.greenButton.setDefault(False)
        self.greenButton.setFlat(False)
        self.greenButton.setObjectName(_fromUtf8("greenButton"))
        self.horizontalLayout_5.addWidget(self.greenButton)
        self.greenSlider = QtGui.QSlider(lightEnginePanel)
        self.greenSlider.setMaximum(255)
        self.greenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.greenSlider.setObjectName(_fromUtf8("greenSlider"))
        self.horizontalLayout_5.addWidget(self.greenSlider)
        self.greenSpinBox = QtGui.QDoubleSpinBox(lightEnginePanel)
        self.greenSpinBox.setDecimals(0)
        self.greenSpinBox.setMaximum(255.0)
        self.greenSpinBox.setSingleStep(10.0)
        self.greenSpinBox.setObjectName(_fromUtf8("greenSpinBox"))
        self.horizontalLayout_5.addWidget(self.greenSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.redButton = QtGui.QPushButton(lightEnginePanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redButton.sizePolicy().hasHeightForWidth())
        self.redButton.setSizePolicy(sizePolicy)
        self.redButton.setMinimumSize(QtCore.QSize(80, 0))
        self.redButton.setText(QtGui.QApplication.translate("lightEnginePanel", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.redButton.setAutoDefault(False)
        self.redButton.setDefault(False)
        self.redButton.setFlat(False)
        self.redButton.setObjectName(_fromUtf8("redButton"))
        self.horizontalLayout_6.addWidget(self.redButton)
        self.redSlider = QtGui.QSlider(lightEnginePanel)
        self.redSlider.setMaximum(255)
        self.redSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redSlider.setObjectName(_fromUtf8("redSlider"))
        self.horizontalLayout_6.addWidget(self.redSlider)
        self.redSpinBox = QtGui.QDoubleSpinBox(lightEnginePanel)
        self.redSpinBox.setDecimals(0)
        self.redSpinBox.setMaximum(255.0)
        self.redSpinBox.setSingleStep(10.0)
        self.redSpinBox.setProperty("value", 0.0)
        self.redSpinBox.setObjectName(_fromUtf8("redSpinBox"))
        self.horizontalLayout_6.addWidget(self.redSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.maxIntensitiesButton = QtGui.QPushButton(lightEnginePanel)
        self.maxIntensitiesButton.setText(QtGui.QApplication.translate("lightEnginePanel", "Set Intensities to Max", None, QtGui.QApplication.UnicodeUTF8))
        self.maxIntensitiesButton.setObjectName(_fromUtf8("maxIntensitiesButton"))
        self.gridLayout.addWidget(self.maxIntensitiesButton, 0, 1, 1, 1)
        self.minIntensitiesButton = QtGui.QPushButton(lightEnginePanel)
        self.minIntensitiesButton.setText(QtGui.QApplication.translate("lightEnginePanel", "Set Intensities to Min", None, QtGui.QApplication.UnicodeUTF8))
        self.minIntensitiesButton.setObjectName(_fromUtf8("minIntensitiesButton"))
        self.gridLayout.addWidget(self.minIntensitiesButton, 1, 1, 1, 1)
        self.enableChannelsButton = QtGui.QPushButton(lightEnginePanel)
        self.enableChannelsButton.setText(QtGui.QApplication.translate("lightEnginePanel", "Enable All Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.enableChannelsButton.setObjectName(_fromUtf8("enableChannelsButton"))
        self.gridLayout.addWidget(self.enableChannelsButton, 0, 0, 1, 1)
        self.disableChannelsButton = QtGui.QPushButton(lightEnginePanel)
        self.disableChannelsButton.setText(QtGui.QApplication.translate("lightEnginePanel", "Disable All Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.disableChannelsButton.setObjectName(_fromUtf8("disableChannelsButton"))
        self.gridLayout.addWidget(self.disableChannelsButton, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(lightEnginePanel)
        QtCore.QMetaObject.connectSlotsByName(lightEnginePanel)

    def retranslateUi(self, lightEnginePanel):
        pass

